type: edu
files:
- name: tests/test_task.py
  visible: false
- name: __init__.py
  visible: false
- name: tests/__init__.py
  visible: false
- name: docker-compose.yaml
  visible: true
- name: gateway/__init__.py
  visible: true
- name: gateway/application.py
  visible: true
- name: gateway/Dockerfile
  visible: true
- name: gateway/requirements.txt
  visible: true
- name: invsys/__init__.py
  visible: true
- name: invsys/api.py
  visible: true
- name: invsys/dal.py
  visible: true
- name: invsys/Dockerfile
  visible: true
- name: invsys/requirements.txt
  visible: true
- name: runConfigurations/Composing_system_docker-compose-test.run.xml
  visible: false
- name: runConfigurations/Composing_the_system_Docker_compose.run.xml
  visible: false
