version: '2'
services:
    gateway:
        build: gateway
        container_name: flask-app-gateway
        image: flask-app-gateway-img
        ports:
            - "5001:5001"
        depends_on:
            invsys:
                condition: service_started

    invsys:
        build: invsys
        container_name: flask-app-invsys
        image: flask-app-invsys-img
        ports:
            - "5000:5000"
