name: LinksChecker

on:
  # Triggers the workflow on push or pull request events for specific branches
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  links-checker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Call the action jetbrains-academy/links-checker-action
        uses: jetbrains-academy/links-checker-action@main
        with:
          dir: ./
